name: AWS Deploy
on: push

env:
  AWS_ROLE_ARN: arn:aws:iam::849178858650:role/terraform-gha-849178858650-20211229 # 作成したIAMロールのARN

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
